package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// --- Classic Timber / Amber Wood Palette ---
val AmberWoodLightPrimary = Color(0xFF85441E)
val AmberWoodLightOnPrimary = Color(0xFFFFFFFF)
val AmberWoodLightPrimaryContainer = Color(0xFFFFDBCB)
val AmberWoodLightOnPrimaryContainer = Color(0xFF341100)

val AmberWoodLightSecondary = Color(0xFF755945)
val AmberWoodLightOnSecondary = Color(0xFFFFFFFF)
val AmberWoodLightSecondaryContainer = Color(0xFFFFDCC5)
val AmberWoodLightOnSecondaryContainer = Color(0xFF2B1708)

val AmberWoodLightTertiary = Color(0xFF4C663D)
val AmberWoodLightOnTertiary = Color(0xFFFFFFFF)
val AmberWoodLightTertiaryContainer = Color(0xFFCEEBB7)
val AmberWoodLightOnTertiaryContainer = Color(0xFF0C2003)

val AmberWoodLightBackground = Color(0xFFFCF8F5)
val AmberWoodLightOnBackground = Color(0xFF211A16)
val AmberWoodLightSurface = Color(0xFFFFFFFF)
val AmberWoodLightOnSurface = Color(0xFF211A16)
val AmberWoodLightSurfaceVariant = Color(0xFFF4E3D8)
val AmberWoodLightOnSurfaceVariant = Color(0xFF52443C)
val AmberWoodLightOutline = Color(0xFF85736A)

// Classic Amber Dark Palette
val AmberWoodDarkPrimary = Color(0xFFFFB68C)
val AmberWoodDarkOnPrimary = Color(0xFF4F2505)
val AmberWoodDarkPrimaryContainer = Color(0xFF6B3413)
val AmberWoodDarkOnPrimaryContainer = Color(0xFFFFDBCB)

val AmberWoodDarkSecondary = Color(0xFFE5BEA6)
val AmberWoodDarkOnSecondary = Color(0xFF432C1B)
val AmberWoodDarkSecondaryContainer = Color(0xFF5B422F)
val AmberWoodDarkOnSecondaryContainer = Color(0xFFFFDCC5)

val AmberWoodDarkTertiary = Color(0xFFB3CE9D)
val AmberWoodDarkOnTertiary = Color(0xFF203613)
val AmberWoodDarkTertiaryContainer = Color(0xFF364E27)
val AmberWoodDarkOnTertiaryContainer = Color(0xFFCEEBB7)

val AmberWoodDarkBackground = Color(0xFF19120E)
val AmberWoodDarkOnBackground = Color(0xFFEFE0D9)
val AmberWoodDarkSurface = Color(0xFF211A15)
val AmberWoodDarkOnSurface = Color(0xFFEFE0D9)
val AmberWoodDarkSurfaceVariant = Color(0xFF52443C)
val AmberWoodDarkOnSurfaceVariant = Color(0xFFD7C2B7)
val AmberWoodDarkOutline = Color(0xFFA08C82)

// --- Red Palette (Crimson & Ruby) ---
val RedLightPrimary = Color(0xFFB3261E)
val RedLightOnPrimary = Color(0xFFFFFFFF)
val RedLightPrimaryContainer = Color(0xFFFFDAD6)
val RedLightOnPrimaryContainer = Color(0xFF410002)
val RedLightSecondary = Color(0xFF904A42)
val RedLightOnSecondary = Color(0xFFFFFFFF)
val RedLightSecondaryContainer = Color(0xFFFFDAD5)
val RedLightOnSecondaryContainer = Color(0xFF3B0907)
val RedLightTertiary = Color(0xFF865324)
val RedLightOnTertiary = Color(0xFFFFFFFF)
val RedLightTertiaryContainer = Color(0xFFFFDCBE)
val RedLightOnTertiaryContainer = Color(0xFF2F1500)
val RedLightBackground = Color(0xFFFFF8F6)
val RedLightOnBackground = Color(0xFF231918)
val RedLightSurface = Color(0xFFFFFFFF)
val RedLightOnSurface = Color(0xFF231918)
val RedLightSurfaceVariant = Color(0xFFF5DDDA)
val RedLightOnSurfaceVariant = Color(0xFF534341)
val RedLightOutline = Color(0xFF857371)

val RedDarkPrimary = Color(0xFFFFB4AB)
val RedDarkOnPrimary = Color(0xFF690005)
val RedDarkPrimaryContainer = Color(0xFF93000A)
val RedDarkOnPrimaryContainer = Color(0xFFFFDAD6)
val RedDarkSecondary = Color(0xFFFFB4A9)
val RedDarkOnSecondary = Color(0xFF561E19)
val RedDarkSecondaryContainer = Color(0xFF73332D)
val RedDarkOnSecondaryContainer = Color(0xFFFFDAD5)
val RedDarkTertiary = Color(0xFFFDB97C)
val RedDarkOnTertiary = Color(0xFF4C2700)
val RedDarkTertiaryContainer = Color(0xFF6A3B0F)
val RedDarkOnTertiaryContainer = Color(0xFFFFDCBE)
val RedDarkBackground = Color(0xFF1A1111)
val RedDarkOnBackground = Color(0xFFF1DFDD)
val RedDarkSurface = Color(0xFF201A1A)
val RedDarkOnSurface = Color(0xFFF1DFDD)
val RedDarkSurfaceVariant = Color(0xFF534341)
val RedDarkOnSurfaceVariant = Color(0xFFD8C2BF)
val RedDarkOutline = Color(0xFFA08C8A)

// --- Blue Palette (Cobalt & Ocean Sapphire) ---
val BlueLightPrimary = Color(0xFF1565C0)
val BlueLightOnPrimary = Color(0xFFFFFFFF)
val BlueLightPrimaryContainer = Color(0xFFD4E3FF)
val BlueLightOnPrimaryContainer = Color(0xFF001C3A)
val BlueLightSecondary = Color(0xFF535F70)
val BlueLightOnSecondary = Color(0xFFFFFFFF)
val BlueLightSecondaryContainer = Color(0xFFD7E3F7)
val BlueLightOnSecondaryContainer = Color(0xFF101C2B)
val BlueLightTertiary = Color(0xFF6C567B)
val BlueLightOnTertiary = Color(0xFFFFFFFF)
val BlueLightTertiaryContainer = Color(0xFFF4DAFF)
val BlueLightOnTertiaryContainer = Color(0xFF261434)
val BlueLightBackground = Color(0xFFF8F9FF)
val BlueLightOnBackground = Color(0xFF191C20)
val BlueLightSurface = Color(0xFFFFFFFF)
val BlueLightOnSurface = Color(0xFF191C20)
val BlueLightSurfaceVariant = Color(0xFFDFE2EB)
val BlueLightOnSurfaceVariant = Color(0xFF43474E)
val BlueLightOutline = Color(0xFF73777F)

val BlueDarkPrimary = Color(0xFFA5C8FF)
val BlueDarkOnPrimary = Color(0xFF00315E)
val BlueDarkPrimaryContainer = Color(0xFF004784)
val BlueDarkOnPrimaryContainer = Color(0xFFD4E3FF)
val BlueDarkSecondary = Color(0xFFBBC7DB)
val BlueDarkOnSecondary = Color(0xFF253140)
val BlueDarkSecondaryContainer = Color(0xFF3B4858)
val BlueDarkOnSecondaryContainer = Color(0xFFD7E3F7)
val BlueDarkTertiary = Color(0xFFD7BEE5)
val BlueDarkOnTertiary = Color(0xFF3C294A)
val BlueDarkTertiaryContainer = Color(0xFF533F62)
val BlueDarkOnTertiaryContainer = Color(0xFFF4DAFF)
val BlueDarkBackground = Color(0xFF111318)
val BlueDarkOnBackground = Color(0xFFE1E2E8)
val BlueDarkSurface = Color(0xFF181C22)
val BlueDarkOnSurface = Color(0xFFE1E2E8)
val BlueDarkSurfaceVariant = Color(0xFF43474E)
val BlueDarkOnSurfaceVariant = Color(0xFFC3C7D0)
val BlueDarkOutline = Color(0xFF8D9199)

// --- Yellow Palette (Sunlit Gold & Amber Ochre) ---
val YellowLightPrimary = Color(0xFFB58500)
val YellowLightOnPrimary = Color(0xFFFFFFFF)
val YellowLightPrimaryContainer = Color(0xFFFFE082)
val YellowLightOnPrimaryContainer = Color(0xFF241A00)
val YellowLightSecondary = Color(0xFF6B5F3E)
val YellowLightOnSecondary = Color(0xFFFFFFFF)
val YellowLightSecondaryContainer = Color(0xFFF5E3B8)
val YellowLightOnSecondaryContainer = Color(0xFF241C03)
val YellowLightTertiary = Color(0xFF496650)
val YellowLightOnTertiary = Color(0xFFFFFFFF)
val YellowLightTertiaryContainer = Color(0xFFCBEBCF)
val YellowLightOnTertiaryContainer = Color(0xFF052110)
val YellowLightBackground = Color(0xFFFFFDF5)
val YellowLightOnBackground = Color(0xFF1F1B14)
val YellowLightSurface = Color(0xFFFFFFFF)
val YellowLightOnSurface = Color(0xFF1F1B14)
val YellowLightSurfaceVariant = Color(0xFFEAE2CF)
val YellowLightOnSurfaceVariant = Color(0xFF4B463A)
val YellowLightOutline = Color(0xFF7D7669)

val YellowDarkPrimary = Color(0xFFFFE082)
val YellowDarkOnPrimary = Color(0xFF3C2F00)
val YellowDarkPrimaryContainer = Color(0xFF574300)
val YellowDarkOnPrimaryContainer = Color(0xFFFFE082)
val YellowDarkSecondary = Color(0xFFD8C79F)
val YellowDarkOnSecondary = Color(0xFF3B3114)
val YellowDarkSecondaryContainer = Color(0xFF524728)
val YellowDarkOnSecondaryContainer = Color(0xFFF5E3B8)
val YellowDarkTertiary = Color(0xFFAFD0B5)
val YellowDarkOnTertiary = Color(0xFF1A3623)
val YellowDarkTertiaryContainer = Color(0xFF314D39)
val YellowDarkOnTertiaryContainer = Color(0xFFCBEBCF)
val YellowDarkBackground = Color(0xFF17130B)
val YellowDarkOnBackground = Color(0xFFEAE1D5)
val YellowDarkSurface = Color(0xFF1F1A12)
val YellowDarkOnSurface = Color(0xFFEAE1D5)
val YellowDarkSurfaceVariant = Color(0xFF4B463A)
val YellowDarkOnSurfaceVariant = Color(0xFFCEC6B4)
val YellowDarkOutline = Color(0xFF979080)

// --- Combined Palette (Red, Blue, and Yellow All Combined) ---
val CombinedLightPrimary = Color(0xFFC62828) // Bold Ruby Red
val CombinedLightOnPrimary = Color(0xFFFFFFFF)
val CombinedLightPrimaryContainer = Color(0xFFFFCDD2)
val CombinedLightOnPrimaryContainer = Color(0xFF5C0003)
val CombinedLightSecondary = Color(0xFF1565C0) // Cobalt Blue
val CombinedLightOnSecondary = Color(0xFFFFFFFF)
val CombinedLightSecondaryContainer = Color(0xFFBBDEFB)
val CombinedLightOnSecondaryContainer = Color(0xFF00227B)
val CombinedLightTertiary = Color(0xFFF57F17) // Radiant Yellow Gold
val CombinedLightOnTertiary = Color(0xFFFFFFFF)
val CombinedLightTertiaryContainer = Color(0xFFFFF9C4)
val CombinedLightOnTertiaryContainer = Color(0xFF563500)
val CombinedLightBackground = Color(0xFFFCFAF7)
val CombinedLightOnBackground = Color(0xFF1E1A18)
val CombinedLightSurface = Color(0xFFFFFFFF)
val CombinedLightOnSurface = Color(0xFF1E1A18)
val CombinedLightSurfaceVariant = Color(0xFFF0E5DF)
val CombinedLightOnSurfaceVariant = Color(0xFF4E4540)
val CombinedLightOutline = Color(0xFF81756F)

val CombinedDarkPrimary = Color(0xFFFF8A80) // Vivid Coral Red
val CombinedDarkOnPrimary = Color(0xFF5E0005)
val CombinedDarkPrimaryContainer = Color(0xFF8E0008)
val CombinedDarkOnPrimaryContainer = Color(0xFFFFCDD2)
val CombinedDarkSecondary = Color(0xFF82B1FF) // Sky Cobalt Blue
val CombinedDarkOnSecondary = Color(0xFF00296B)
val CombinedDarkSecondaryContainer = Color(0xFF0043A8)
val CombinedDarkOnSecondaryContainer = Color(0xFFD1E4FF)
val CombinedDarkTertiary = Color(0xFFFFE082) // Luminous Sunflower Yellow
val CombinedDarkOnTertiary = Color(0xFF422B00)
val CombinedDarkTertiaryContainer = Color(0xFF5F4100)
val CombinedDarkOnTertiaryContainer = Color(0xFFFFF9C4)
val CombinedDarkBackground = Color(0xFF141215)
val CombinedDarkOnBackground = Color(0xFFEDE0DB)
val CombinedDarkSurface = Color(0xFF1E1B20)
val CombinedDarkOnSurface = Color(0xFFEDE0DB)
val CombinedDarkSurfaceVariant = Color(0xFF4B4348)
val CombinedDarkOnSurfaceVariant = Color(0xFFCDC3C7)
val CombinedDarkOutline = Color(0xFF968D92)


